/**
 * Local, offline content editor for ../data.js
 * -------------------------------------------
 * This file makes NO network requests, stores NO passwords, tokens or
 * secrets, and never talks to GitHub. It only reads a file you choose
 * from your computer and lets you download an edited replacement.
 *
 * Publishing the change still requires YOUR GitHub login when you commit
 * the exported data.js — that real authentication is what keeps editing
 * private, without this tool needing any backend of its own.
 */
(function () {
  "use strict";

  var DEFAULT_DATA = {
    profile: {
      name: "", title: "", location: "", tagline: "", objective: "",
      email: "", phone: "", linkedin: "", github: "", resumeFile: "assets/resume.pdf"
    },
    skills: [],
    experience: [],
    projects: [],
    certifications: [],
    education: []
  };

  var state = null;

  var root = document.getElementById("admin-root");
  var importInput = document.getElementById("import-file");
  var exportBtn = document.getElementById("export-btn");
  var startBlankBtn = document.getElementById("start-blank");

  /* ------------------------------------------------------------------ */
  /* Import / Export                                                     */
  /* ------------------------------------------------------------------ */
  importInput.addEventListener("change", function (e) {
    var file = e.target.files[0];
    if (!file) return;
    var reader = new FileReader();
    reader.onload = function () {
      try {
        state = parseDataJs(reader.result);
        render();
      } catch (err) {
        alert("Couldn't read that file as a valid data.js export. Make sure you selected the correct data.js file.\n\n" + err.message);
      }
    };
    reader.readAsText(file);
  });

  startBlankBtn.addEventListener("click", function () {
    state = JSON.parse(JSON.stringify(DEFAULT_DATA));
    render();
  });

  exportBtn.addEventListener("click", function () {
    if (!state) { alert("Import or start a data.js first."); return; }
    var text =
      "/* Generated by admin/admin.html — replace your existing data.js with this file. */\n" +
      "window.PORTFOLIO_DATA = " + JSON.stringify(state, null, 2) + ";\n";
    var blob = new Blob([text], { type: "text/javascript" });
    var url = URL.createObjectURL(blob);
    var a = document.createElement("a");
    a.href = url;
    a.download = "data.js";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  });

  function parseDataJs(text) {
    var marker = "window.PORTFOLIO_DATA";
    var idx = text.indexOf(marker);
    if (idx === -1) throw new Error("Missing 'window.PORTFOLIO_DATA' assignment.");
    var eq = text.indexOf("=", idx);
    var jsonPart = text.slice(eq + 1).trim();
    if (jsonPart.endsWith(";")) jsonPart = jsonPart.slice(0, -1);
    var parsed = JSON.parse(jsonPart);
    // fill in any missing top-level keys so the editor never breaks
    return Object.assign({}, DEFAULT_DATA, parsed);
  }

  /* ------------------------------------------------------------------ */
  /* Generic helpers                                                     */
  /* ------------------------------------------------------------------ */
  function el(tag, opts) {
    opts = opts || {};
    var n = document.createElement(tag);
    if (opts.class) n.className = opts.class;
    if (opts.text) n.textContent = opts.text;
    if (opts.attrs) Object.keys(opts.attrs).forEach(function (k) { n.setAttribute(k, opts.attrs[k]); });
    return n;
  }

  function field(labelText, value, onChange, multiline) {
    var wrap = el("div", { class: "field" });
    wrap.appendChild(el("label", { text: labelText }));
    var input = el(multiline ? "textarea" : "input", {});
    if (!multiline) input.type = "text";
    input.value = value || "";
    input.addEventListener("input", function () { onChange(input.value); });
    wrap.appendChild(input);
    return wrap;
  }

  // editable list of plain strings (e.g. skill items, tools, highlights)
  function listField(labelText, arr, onChange) {
    var wrap = el("div", { class: "field" });
    wrap.appendChild(el("label", { text: labelText }));
    var listWrap = el("div", { class: "list-field" });

    function renderRows() {
      listWrap.innerHTML = "";
      arr.forEach(function (val, i) {
        var row = el("div", { class: "list-item-row" });
        var input = el("input", { attrs: { type: "text" } });
        input.value = val;
        input.addEventListener("input", function () { arr[i] = input.value; onChange(arr); });
        row.appendChild(input);
        var rm = el("button", { class: "btn btn-sm btn-danger", text: "Remove", attrs: { type: "button" } });
        rm.addEventListener("click", function () { arr.splice(i, 1); onChange(arr); renderRows(); });
        row.appendChild(rm);
        listWrap.appendChild(row);
      });
      var addBtn = el("button", { class: "btn btn-sm btn-ghost", text: "+ Add item", attrs: { type: "button" } });
      addBtn.addEventListener("click", function () { arr.push(""); onChange(arr); renderRows(); });
      listWrap.appendChild(addBtn);
    }
    renderRows();
    wrap.appendChild(listWrap);
    return wrap;
  }

  /* ------------------------------------------------------------------ */
  /* Section builders                                                    */
  /* ------------------------------------------------------------------ */
  function buildProfileSection() {
    var section = el("section", { class: "admin-section" });
    var head = el("div", { class: "admin-section-head" });
    head.appendChild(el("h2", { text: "Profile & About" }));
    section.appendChild(head);
    var body = el("div", { class: "admin-section-body" });
    var card = el("div", { class: "entry-card" });

    var p = state.profile;
    var row1 = el("div", { class: "field-row" });
    row1.appendChild(field("Full name", p.name, function (v) { p.name = v; }));
    row1.appendChild(field("Title", p.title, function (v) { p.title = v; }));
    card.appendChild(row1);

    var row2 = el("div", { class: "field-row" });
    row2.appendChild(field("Location", p.location, function (v) { p.location = v; }));
    row2.appendChild(field("Resume file path", p.resumeFile, function (v) { p.resumeFile = v; }));
    card.appendChild(row2);

    card.appendChild(field("Hero tagline (short)", p.tagline, function (v) { p.tagline = v; }));
    card.appendChild(field("About / objective (paragraph)", p.objective, function (v) { p.objective = v; }, true));

    var row3 = el("div", { class: "field-row" });
    row3.appendChild(field("Email", p.email, function (v) { p.email = v; }));
    row3.appendChild(field("Phone", p.phone, function (v) { p.phone = v; }));
    card.appendChild(row3);

    var row4 = el("div", { class: "field-row" });
    row4.appendChild(field("LinkedIn URL", p.linkedin, function (v) { p.linkedin = v; }));
    row4.appendChild(field("GitHub URL", p.github, function (v) { p.github = v; }));
    card.appendChild(row4);

    body.appendChild(card);
    section.appendChild(body);
    return section;
  }

  // generic repeatable-entry section (skills, experience, projects, certifications, education)
  function buildListSection(title, arr, emptyItemFactory, fieldsBuilder) {
    var section = el("section", { class: "admin-section" });
    var head = el("div", { class: "admin-section-head" });
    head.appendChild(el("h2", { text: title }));
    var addBtn = el("button", { class: "btn btn-sm btn-ghost", text: "+ Add", attrs: { type: "button" } });
    head.appendChild(addBtn);
    section.appendChild(head);

    var body = el("div", { class: "admin-section-body" });
    section.appendChild(body);

    function renderEntries() {
      body.innerHTML = "";
      if (!arr.length) {
        body.appendChild(el("p", { text: "Nothing here yet — click \u201c+ Add\u201d to create one." }));
      }
      arr.forEach(function (item, i) {
        var card = el("div", { class: "entry-card" });
        var cardHead = el("div", { class: "entry-card-head" });
        cardHead.appendChild(el("span", { class: "tag", text: title.replace(/s$/, "") + " " + (i + 1) }));
        var rm = el("button", { class: "btn btn-sm btn-danger", text: "Remove", attrs: { type: "button" } });
        rm.addEventListener("click", function () {
          if (confirm("Remove this entry?")) { arr.splice(i, 1); renderEntries(); }
        });
        cardHead.appendChild(rm);
        card.appendChild(cardHead);
        fieldsBuilder(card, item, renderEntries);
        body.appendChild(card);
      });
    }

    addBtn.addEventListener("click", function () {
      arr.push(emptyItemFactory());
      renderEntries();
    });

    renderEntries();
    return section;
  }

  /* ------------------------------------------------------------------ */
  /* Main render                                                         */
  /* ------------------------------------------------------------------ */
  function render() {
    root.innerHTML = "";

    root.appendChild(buildProfileSection());

    root.appendChild(buildListSection("Skills", state.skills,
      function () { return { category: "", items: [] }; },
      function (card, item, refresh) {
        card.appendChild(field("Category name", item.category, function (v) { item.category = v; }));
        card.appendChild(listField("Skills in this category", item.items, function () {}));
      }));

    root.appendChild(buildListSection("Experience", state.experience,
      function () { return { company: "", role: "", location: "", startDate: "", endDate: "", highlights: [] }; },
      function (card, item) {
        var r1 = el("div", { class: "field-row" });
        r1.appendChild(field("Company", item.company, function (v) { item.company = v; }));
        r1.appendChild(field("Role", item.role, function (v) { item.role = v; }));
        card.appendChild(r1);
        var r2 = el("div", { class: "field-row" });
        r2.appendChild(field("Location", item.location, function (v) { item.location = v; }));
        r2.appendChild(field("", "", function () {}));
        card.appendChild(r2);
        var r3 = el("div", { class: "field-row" });
        r3.appendChild(field("Start date", item.startDate, function (v) { item.startDate = v; }));
        r3.appendChild(field("End date (use \"Present\" if current)", item.endDate, function (v) { item.endDate = v; }));
        card.appendChild(r3);
        card.appendChild(listField("Highlights / responsibilities", item.highlights, function () {}));
      }));

    root.appendChild(buildListSection("Projects", state.projects,
      function () { return { name: "", tools: [], description: "", highlights: [], insight: "", projectUrl: "", githubUrl: "" }; },
      function (card, item) {
        card.appendChild(field("Project name", item.name, function (v) { item.name = v; }));
        card.appendChild(listField("Tools used", item.tools, function () {}));
        card.appendChild(field("Short description", item.description, function (v) { item.description = v; }, true));
        card.appendChild(listField("Key work (bullet points)", item.highlights, function () {}));
        card.appendChild(field("Key insight / outcome (optional)", item.insight, function (v) { item.insight = v; }, true));
        var r = el("div", { class: "field-row" });
        r.appendChild(field("Project URL (leave blank if none)", item.projectUrl, function (v) { item.projectUrl = v; }));
        r.appendChild(field("GitHub URL (leave blank if none)", item.githubUrl, function (v) { item.githubUrl = v; }));
        card.appendChild(r);
      }));

    root.appendChild(buildListSection("Certifications", state.certifications,
      function () { return { name: "", institute: "", date: "", image: "assets/certificates/" }; },
      function (card, item) {
        var r1 = el("div", { class: "field-row" });
        r1.appendChild(field("Certificate name", item.name, function (v) { item.name = v; }));
        r1.appendChild(field("Issuing institute", item.institute, function (v) { item.institute = v; }));
        card.appendChild(r1);
        var r2 = el("div", { class: "field-row" });
        r2.appendChild(field("Date / duration", item.date, function (v) { item.date = v; }));
        r2.appendChild(field("Image path (place the file in assets/certificates/)", item.image, function (v) { item.image = v; }));
        card.appendChild(r2);
      }));

    root.appendChild(buildListSection("Education", state.education,
      function () { return { degree: "", institute: "", location: "", startYear: "", endYear: "" }; },
      function (card, item) {
        var r1 = el("div", { class: "field-row" });
        r1.appendChild(field("Degree", item.degree, function (v) { item.degree = v; }));
        r1.appendChild(field("Institute", item.institute, function (v) { item.institute = v; }));
        card.appendChild(r1);
        var r2 = el("div", { class: "field-row" });
        r2.appendChild(field("Location", item.location, function (v) { item.location = v; }));
        r2.appendChild(field("", "", function () {}));
        card.appendChild(r2);
        var r3 = el("div", { class: "field-row" });
        r3.appendChild(field("Start year", item.startYear, function (v) { item.startYear = v; }));
        r3.appendChild(field("End year", item.endYear, function (v) { item.endYear = v; }));
        card.appendChild(r3);
      }));
  }
})();
